//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2new.Models
{
    using System;
    using System.Data.Entity;
    using System.Data;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class naviEntities1 : DbContext
    {
        public naviEntities1()
            : base("name=naviEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<table3> table3 { get; set; }
    
        public virtual System.Data.Entity.Core.Objects.ObjectResult<pro1_Result> pro1(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new System.Data.Entity.Core.Objects.ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro1_Result>("pro1", emailParameter, passwordParameter);
        }
    }
}
